/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import bd.DAO;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.PrimitiveIterator;
import java.util.Random;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import model.Correo;
import model.Rut;
import model.Usuario;

/**
 *
 * @author Javier
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        setTitle("BancoFunaoApp");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblRut = new javax.swing.JLabel();
        lblClave = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        txtClave = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        btnIngTrabaja = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 14))); // NOI18N
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/30818 (1).png"))); // NOI18N
        panelLogin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/b427c272b21c80f9bddea2d6d9dbe733-equipo-ejecutivo-gente-by-vexels.png"))); // NOI18N
        panelLogin.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        jLabel4.setText("LOGIN");
        panelLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 70, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono-ingresar-png (2).png"))); // NOI18N
        panelLogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        lblRut.setText("Rut:");
        panelLogin.add(lblRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 38, 24));

        lblClave.setText("Clave:");
        panelLogin.add(lblClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 22));

        txtRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRutKeyReleased(evt);
            }
        });
        panelLogin.add(txtRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 165, -1));
        panelLogin.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 125, -1));

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        panelLogin.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, 30));

        btnIngTrabaja.setText("Ingreso Trabajadores");
        btnIngTrabaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngTrabajaActionPerformed(evt);
            }
        });
        panelLogin.add(btnIngTrabaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        btnRegistro.setText("Registro");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        panelLogin.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, 30));

        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sin puntos \".\" ni  guion \"-\" "); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, 37));
        jLabel1.getAccessibleContext().setAccessibleName("Con puntos \".\" y guion \"-\" \nEj: 1.111.111-1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cuáles-son-los-colores-pasteles-300x300 (1).jpg"))); // NOI18N
        panelLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        try {
            // TODO add your handling code here:
            DAO oDao = new DAO();
            Usuario oUsuario = oDao.isUsuario(txtRut.getText(), txtClave.getText());
            PantallaP oPantallaP;
            System.out.println("" + txtRut.getText() + txtClave.getText());
            String rutU = txtRut.getText();
            System.out.println(rutU);
            if (oUsuario != null) {
                if (oUsuario.isEstado()) {
                    JOptionPane.showMessageDialog(rootPane, "Bienvenido " + oUsuario.getNombre());
                    Correo oCorreo = new Correo();
                    oCorreo.enviarCorreo(oUsuario.getCorreo(), "Has iniciado sesion? ", " " + oUsuario.getNombre() + " Hemos"
                            + " detectado que has iniciado"
                            + " sesion en nuestra banca movil,"
                            + " si has sido tu ignora este mensaje.");
                    oPantallaP = new PantallaP(txtRut.getText());
                    oPantallaP.setVisible(true);

//                System.out.println(rutU);
//                oPantallaP.rutUsuario=oUsuario.getRut();
//                System.out.println(oPantallaP.rutUsuario);
//                oPantallaP.txtN_Cuenta.setText(String.valueOf(oUsuario.getN_cuenta()));
//                oPantallaP.txtSaldo.setText(String.valueOf(oUsuario.getSaldo()));
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Su cuenta esta desactivada\n acuda a servicio al cliente", "Error", JOptionPane.WARNING_MESSAGE);
                    txtRut.setText("");
                    txtClave.setText("");
                    txtRut.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Error al ingresar \n 1.- El usuario no existe "
                        + "\n 2.- Uno de los campos es incorrecto");
                txtRut.setText("");
                txtClave.setText("");
                txtRut.requestFocus();
            }

        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnIngTrabajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngTrabajaActionPerformed
        // TODO add your handling code here:
        LogTrabajador oLogTrabajador = new LogTrabajador();
        oLogTrabajador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIngTrabajaActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
        RegistroUser oRegistroUser = new RegistroUser();
        oRegistroUser.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void txtRutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutKeyReleased
        // TODO add your handling code here:
        Rut oRut = new Rut();
        txtRut.setText(oRut.formatear(txtRut.getText()));
        /*
        if(!oRut.validar(txtRut.getText())){
            JOptionPane.showMessageDialog(rootPane, "Digito verificador invalido");
        }else{
            
        }
         */
    }//GEN-LAST:event_txtRutKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngTrabaja;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblRut;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables
}
