/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import bd.DAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Rut;
import model.Trabajador;

/**
 *
 * @author Javier
 */
public class LogTrabajador extends javax.swing.JFrame {

    /**
     * Creates new form LogTrabajador
     */
    public LogTrabajador() {
        initComponents();
        setTitle("BancoFunaoApp");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        panelTrabajador = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRutT = new javax.swing.JTextField();
        txtClaveT = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelTrabajador.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panelTrabajador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        jLabel6.setText("LOGIN");
        panelTrabajador.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        jLabel1.setText("Rut:");
        panelTrabajador.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 51, -1, -1));

        jLabel2.setText("Clave: ");
        panelTrabajador.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 97, -1, -1));

        txtRutT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRutTKeyReleased(evt);
            }
        });
        panelTrabajador.add(txtRutT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 48, 146, -1));
        panelTrabajador.add(txtClaveT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 94, 146, -1));

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        panelTrabajador.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 145, -1, -1));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        panelTrabajador.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 145, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cuáles-son-los-colores-pasteles-300x300 (1).jpg"))); // NOI18N
        panelTrabajador.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        try {
            // TODO add your handling code here:
            DAO oDao = new DAO();
            Trabajador oTrabajador;
            oTrabajador = oDao.isTrabajador(txtRutT.getText(), txtClaveT.getText());
            if (oTrabajador != null) {
                JOptionPane.showMessageDialog(rootPane, "Bienvenido " + oTrabajador.getNombre());
                Solicitudes oSolicitudes = new Solicitudes(txtRutT.getText());
                oSolicitudes.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Error al ingresar \n 1.- El usuario no existe "
                        + "\n 2.- Uno de los campos es incorrecto");
                txtRutT.setText("");
                txtClaveT.setText("");
                txtRutT.requestFocus();
            }

        } catch (SQLException ex) {
            Logger.getLogger(LogTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        Login oLogin=new Login();
        oLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtRutTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutTKeyReleased
        // TODO add your handling code here:
        Rut oRut=new Rut();
        txtRutT.setText(oRut.formatear(txtRutT.getText()));
    }//GEN-LAST:event_txtRutTKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LogTrabajador().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panelTrabajador;
    private javax.swing.JPasswordField txtClaveT;
    private javax.swing.JTextField txtRutT;
    // End of variables declaration//GEN-END:variables

}
