/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import app.Login;
import bd.DAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Correo;
import model.Rut;

/**
 *
 * @author Javier
 */
public class RegistroUser extends javax.swing.JFrame {

    /**
     * Creates new form RegistroUser
     */
    public RegistroUser() {
        initComponents();
        setTitle("BancoFunaoApp");
        //seterRut(txtRut.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRegistro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApPaterno = new javax.swing.JTextField();
        txtApMaterno = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInfo = new javax.swing.JTextArea();
        btnRegistro = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Rut:");
        panelRegistro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 33, -1, -1));

        jLabel2.setText("Nombres:");
        panelRegistro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 71, -1, -1));

        jLabel3.setText("Apellido Paterno:");
        panelRegistro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 109, -1, -1));

        jLabel4.setText("Apellido Materno:");
        panelRegistro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 147, -1, -1));

        jLabel5.setText("Correo: ");
        panelRegistro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 185, -1, -1));

        txtRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutActionPerformed(evt);
            }
        });
        txtRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRutKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRutKeyReleased(evt);
            }
        });
        panelRegistro.add(txtRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 30, 148, -1));

        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        panelRegistro.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 68, 148, -1));
        panelRegistro.add(txtApPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 106, 148, -1));
        panelRegistro.add(txtApMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 144, 146, -1));
        panelRegistro.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 182, 146, -1));

        txtInfo.setColumns(20);
        txtInfo.setRows(5);
        txtInfo.setText("Cuando inicie sesión se solicitara su \nclave la cual seran los ultimos 4 \ndigitos de su rut antes del digito \nverificador.");
        jScrollPane1.setViewportView(txtInfo);

        panelRegistro.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 286, 335, -1));

        btnRegistro.setText("Registrar");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        panelRegistro.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 235, -1, -1));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        panelRegistro.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 235, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cuáles-son-los-colores-pasteles-300x300 (1).jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        panelRegistro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void txtRutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutKeyPressed

    private void txtRutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutKeyReleased
        // TODO add your handling code here:
        Rut oRut=new Rut();
        txtRut.setText(oRut.formatear(txtRut.getText()));
    }//GEN-LAST:event_txtRutKeyReleased

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
        String rutN=txtRut.getText();
        String a=(rutN.substring(5,6)+rutN.substring(7,10));
        System.out.println(a);
        String b=(rutN.substring(0, 2)+rutN.substring(3, 6)+rutN.substring(7, 10));
        int c=Integer.parseInt(b);
        try {
            DAO oDao=new DAO();
            oDao.crearUsuario(c,txtRut.getText(),txtNombres.getText(),txtApPaterno.getText(),
                    txtApMaterno.getText(),txtCorreo.getText(),a,0);
            JOptionPane.showMessageDialog(rootPane, "Registro Completado");
            Correo oCorreo=new Correo();
            oCorreo.enviarCorreo(txtCorreo.getText(), "Bienvenido A BancoFunao", "Bienvienido/a\n "+txtNombres.getText()+""
                    + " Tu clave para ingresar a la app es "+c+" , al primer inicio debes cambiar la clave.");
            Login oLogin=new Login();
            oLogin.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(RegistroUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        Login oLogin=new Login();
        oLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelRegistro;
    private javax.swing.JTextField txtApMaterno;
    private javax.swing.JTextField txtApPaterno;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextArea txtInfo;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables

//    private void seterRut(String rut){
//        String rutN=rut;
//        if (rutN.length()==8) {
//            String rutF=rutN.substring(0, 1)+"."+rutN.substring(1,4)+"."+rutN.substring(4, 7)+"-"+rutN.substring(7,8);
//            System.out.println(rutF);
//            txtRut.setText(rutN.substring(0, 1)+"."+rutN.substring(1,4)+"."+rutN.substring(4, 7)+"-"+rutN.substring(7,8));
//        }else{ 
//            if (rutN.length()==9) {
//                String rutF=rutN.substring(0, 2)+"."+rutN.substring(2,5)+"."+rutN.substring(5, 8)+"-"+rutN.substring(8,9);  
//                System.out.println(rutF);
//                txtRut.setText(rutN.substring(0, 2)+"."+rutN.substring(2,5)+"."+rutN.substring(5, 8)+"-"+rutN.substring(8,9));
//            }
//        }
//    }
    
}