/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import bd.DAO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Motivo;
import model.Rut;
import model.Usuario;

/**
 *
 * @author Javier
 */
public class Solicitudes extends javax.swing.JFrame {

    String rutString;
    DAO oDao;

    /**
     * Creates new form Solicitudes
     *
     * @param rutTrabajador
     */
    public Solicitudes(String rutTrabajador) {
        rutString = rutTrabajador;
        
        initComponents();
        setTitle("BancoFunaoApp");
        this.setLocationRelativeTo(null);
        cargarCbo();

    }

    private Solicitudes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtRutUsu = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombreUsu = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnEnviar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNcuenta = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        lblEstado = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        cboMotivo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Rut Usuario: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 35, -1, -1));

        txtRutUsu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRutUsuKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRutUsuKeyTyped(evt);
            }
        });
        jPanel1.add(txtRutUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 32, 164, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 31, -1, -1));

        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setText("Apellido Paterno:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 134, -1, -1));

        jLabel4.setText("Apellido Materno:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 134, -1, -1));

        jLabel5.setText("Correo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 181, -1, -1));

        txtNombreUsu.setEditable(false);
        jPanel1.add(txtNombreUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 87, 148, -1));

        txtApellido.setEditable(false);
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 131, 98, -1));

        txtApellidoM.setEditable(false);
        jPanel1.add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 131, 112, -1));

        txtCorreo.setEditable(false);
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 178, 113, -1));

        jLabel6.setText("Detalle solicitud:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 283, -1, -1));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 283, 262, -1));

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 397, -1, -1));

        jLabel7.setText("Cuenta Nº:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 90, -1, -1));

        txtNcuenta.setEditable(false);
        jPanel1.add(txtNcuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 87, 112, -1));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 397, -1, -1));

        lblEstado.setText("Estado Cuenta:");
        jPanel1.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 181, -1, -1));

        txtEstado.setEditable(false);
        jPanel1.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 178, 112, -1));

        cboMotivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione una opcion" }));
        cboMotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMotivoActionPerformed(evt);
            }
        });
        jPanel1.add(cboMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 232, -1, -1));

        jLabel8.setText("Motivo: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 235, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cuáles-son-los-colores-pasteles-300x300 (1).jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        Rut oRut = new Rut();
        if (oRut.validar(txtRutUsu.getText())) {
            getUsuario(txtRutUsu.getText());
        } else {
            JOptionPane.showMessageDialog(rootPane, "Digito verificador incorrecto", "Alerta!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        int n = 0;
        try {
            // TODO add your handling code here:
            oDao = new DAO();
            switch (cboMotivo.getSelectedIndex()) {
                case 0:
                    JOptionPane.showMessageDialog(rootPane, "Debe selecionar una opcion");
                    break;
                case 1:
                    n = cboMotivo.getSelectedIndex();
                    oDao.estadoCuenta(Integer.parseInt(txtNcuenta.getText()), 1);
                    oDao.solicitud(Integer.parseInt(txtNcuenta.getText()), rutString, txtDescripcion.getText(), n);
                    JOptionPane.showMessageDialog(rootPane, "Enviada");
                    break;
                case 2:
                    n = cboMotivo.getSelectedIndex();
                    oDao.estadoCuenta(Integer.parseInt(txtNcuenta.getText()), 0);
                    oDao.solicitud(Integer.parseInt(txtNcuenta.getText()), rutString, txtDescripcion.getText(), n);
                    JOptionPane.showMessageDialog(rootPane, "Enviada");
                    break;
                case 3:
                    n = cboMotivo.getSelectedIndex();
                    oDao.solicitud(Integer.parseInt(txtNcuenta.getText()), rutString, txtDescripcion.getText(), n);
                    JOptionPane.showMessageDialog(rootPane, "Enviada");
                    break;
                case 4:
                    n = cboMotivo.getSelectedIndex();
                    oDao.solicitud(Integer.parseInt(txtNcuenta.getText()), rutString, txtDescripcion.getText(), n);
                    JOptionPane.showMessageDialog(rootPane, "Enviada");
                    break;
                case 5:
                    n = cboMotivo.getSelectedIndex();
                    oDao.solicitud(Integer.parseInt(txtNcuenta.getText()), rutString, txtDescripcion.getText(), n);
                    JOptionPane.showMessageDialog(rootPane, "Enviada");
                    break;
                default:
                    break;
            }
//            oDao.solicitud(Integer.parseInt(txtNcuenta.getText()), rutString, txtDescripcion.getText(), n);
//            JOptionPane.showMessageDialog(rootPane, "Enviada");
            txtRutUsu.setText("");
            txtNombreUsu.setText("");
            txtNcuenta.setText("");
            txtApellido.setText("");
            txtApellidoM.setText("");
            txtCorreo.setText("");
            txtDescripcion.setText("");
            txtEstado.setText("");
            
        } catch (SQLException ex) {
            Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        LogTrabajador oLogTrabajador = new LogTrabajador();
        oLogTrabajador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtRutUsuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutUsuKeyReleased
        // TODO add your handling code here:
        Rut oRut = new Rut();
        txtRutUsu.setText(oRut.formatear(txtRutUsu.getText()));
    }//GEN-LAST:event_txtRutUsuKeyReleased

    private void txtRutUsuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutUsuKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtRutUsuKeyTyped

    private void cboMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMotivoActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_cboMotivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Solicitudes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Solicitudes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Solicitudes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Solicitudes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Solicitudes().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cboMotivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNcuenta;
    private javax.swing.JTextField txtNombreUsu;
    private javax.swing.JTextField txtRutUsu;
    // End of variables declaration//GEN-END:variables

    private void getUsuario(String r_Usuario) {

        try {
            oDao = new DAO();
            Usuario oUsuario;
            oUsuario = oDao.getUserRegisted(r_Usuario);
            if (oUsuario != null) {
                txtNombreUsu.setText(oUsuario.getNombre());
                txtApellido.setText(oUsuario.getApellido_paterno());
                txtApellidoM.setText(oUsuario.getApellido_materno());
                txtCorreo.setText(oUsuario.getCorreo());
                txtNcuenta.setText("" + oUsuario.getN_cuenta());
                if (oUsuario.isEstado()) {
                    txtEstado.setText("Activa");
                } else {
                    txtEstado.setText("Desactiva");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(PantallaP.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void cargarCbo() {
        cboMotivo.removeAllItems();
        cboMotivo.addItem("Seleccione un motivo");
        try {
            oDao = new DAO();
            List<Motivo> motivo = oDao.getMotivo();
            for (Motivo motivo1 : motivo) {
                cboMotivo.addItem(motivo1.getDetalle());
            }
//            if (oMotivo!=null) {                
//                cboMotivo.addItem(oMotivo.getDetalle());
//            }

        } catch (SQLException ex) {
            Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
