/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import bd.DAO;
import java.sql.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Correo;
import model.Rut;
import model.Usuario;

/**
 *
 * @author Javier
 */
public class Transferir extends javax.swing.JFrame {

    DAO oDao;
    DAO oDao2;
    int cuentaOri;

    /**
     * Creates new form Transferir
     *
     * @param cuentaInt
     */
    public Transferir(int cuentaInt) {
        initComponents();
        cuentaOri = cuentaInt;
        txtCuentaOri.setText("" + cuentaOri);
        setTitle("BancoFunaoApp");
        this.setLocationRelativeTo(null);

    }

    Transferir() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTrans = new javax.swing.JPanel();
        txtCuentaOri = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        lblDestino = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRutDes = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNombreDes = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        btnTransferir = new javax.swing.JButton();
        chbConfirmar = new javax.swing.JCheckBox();
        btnVolver = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelTrans.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCuentaOri.setEditable(false);
        panelTrans.add(txtCuentaOri, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 45, 149, -1));

        jLabel1.setText("Desde:");
        panelTrans.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 11, 47, 23));

        jLabel2.setText("Hacia:");
        panelTrans.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 83, 38, 26));

        txtDestino.setEditable(false);
        panelTrans.add(txtDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 157, 157, -1));

        lblDestino.setText("Nº de Cuenta:");
        panelTrans.add(lblDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 157, -1, -1));

        jLabel3.setText("Rut:");
        panelTrans.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 120, -1, -1));

        txtRutDes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRutDesKeyReleased(evt);
            }
        });
        panelTrans.add(txtRutDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 117, 157, -1));

        btnBuscar.setText("Buscar Destinatario");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        panelTrans.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 116, -1, -1));

        jLabel4.setText("Nombre: ");
        panelTrans.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 198, -1, -1));

        txtNombreDes.setEditable(false);
        panelTrans.add(txtNombreDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 195, 157, -1));

        jLabel5.setText("Monto: ");
        panelTrans.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 274, -1, -1));
        panelTrans.add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 271, 157, -1));

        btnTransferir.setText("Transferir");
        btnTransferir.setEnabled(false);
        btnTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirActionPerformed(evt);
            }
        });
        panelTrans.add(btnTransferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 337, -1, -1));

        chbConfirmar.setText("Confirmar Datos");
        chbConfirmar.setEnabled(false);
        chbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbConfirmarActionPerformed(evt);
            }
        });
        panelTrans.add(chbConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 337, -1, -1));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        panelTrans.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));

        jLabel6.setText("Correo:");
        panelTrans.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 236, -1, -1));

        txtCorreo.setEditable(false);
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        panelTrans.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 233, 157, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cuáles-son-los-colores-pasteles-300x300 (1).jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        panelTrans.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed
        // TODO add your handling code here:
        //getRutUsuario(Integer.parseInt(txtCuentaOri.getText()));
        TransferirMonto(cuentaOri, Integer.parseInt(txtDestino.getText()),
                Integer.parseInt(txtMonto.getText()), getRutUsuario(Integer.parseInt(txtCuentaOri.getText())), txtCorreo.getText());
//        enviarCorreo(txtDestino.getText(), Integer.parseInt(txtCuentaOri.getText()), Integer.parseInt(txtMonto.getText()));


    }//GEN-LAST:event_btnTransferirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:    
        getUsuario(txtRutDes.getText());
        if (txtDestino.getText().equalsIgnoreCase(txtCuentaOri.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Imposible de realizar");
            chbConfirmar.setEnabled(false);
            txtRutDes.setText("");
            txtDestino.setText("");
            txtNombreDes.setText("");
        } else if (txtDestino.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Imposible de realizar, Ingrese un rut");
            txtRutDes.setText("");
            txtDestino.setText("");
            txtNombreDes.setText("");
            chbConfirmar.setEnabled(false);
        } else {
            //JOptionPane.showMessageDialog(rootPane, "El usuario que busca \n no tiene una cuenta");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void chbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbConfirmarActionPerformed
        // TODO add your handling code here:
        if (chbConfirmar.isSelected()) {
            btnTransferir.setEnabled(true);
            txtRutDes.setEnabled(false);
            txtMonto.setEnabled(false);
        } else {
            btnTransferir.setEnabled(true);
            txtRutDes.setEnabled(true);
            txtMonto.setEnabled(true);
        }
    }//GEN-LAST:event_chbConfirmarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        PantallaP oPantallaP = new PantallaP(getRutUsuario(cuentaOri));
        oPantallaP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtRutDesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutDesKeyReleased
        // TODO add your handling code here:
        Rut oRut = new Rut();
        txtRutDes.setText(oRut.formatear(txtRutDes.getText()));
    }//GEN-LAST:event_txtRutDesKeyReleased

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Transferir().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnTransferir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JCheckBox chbConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JPanel panelTrans;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCuentaOri;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNombreDes;
    private javax.swing.JTextField txtRutDes;
    // End of variables declaration//GEN-END:variables

    private void TransferirMonto(int _Origen, int _Destino, int _Monto, String rutVolver, String correo) {
        try {
            oDao = new DAO();
            //oDao2=new DAO();
            Usuario oUsuario = new Usuario();
            oUsuario = oDao.getUserRegisted(rutVolver);
            //oUsuario.getSaldo();
            PantallaP oPantallaP;
            if (_Monto > 0 && _Monto < oUsuario.getSaldo()) {
                java.util.Date ahora = new java.util.Date();
                SimpleDateFormat formateador = new SimpleDateFormat("dd-MM-yyyy-HH-mm-ss");
                String fecha = formateador.format(ahora);
                oDao.transferencia(_Origen, _Destino, _Monto);
                JOptionPane.showMessageDialog(rootPane, "Transferencia Exitosa");
                Correo oCorreo = new Correo();
                Usuario oUsuario1 = oDao.getUserRegisted(_Destino);
                oCorreo.enviarCorreo(correo, "Notificacion de Transferencia", "Estimado/a "
                        + "" + oUsuario1.getNombre() + ", le informamos que con fecha "+fecha+", El Cliente "
                        + oUsuario.getNombre() + " le ha transferido un monto de: " + _Monto);
                oCorreo.enviarCorreo(oUsuario.getCorreo(), "Notificacion de Transferencia", "Estimado/a "
                        + "" + oUsuario.getNombre() + ", le informamos que con fecha "+fecha+","
                        + " has realizado una transferencia a "
                        + oUsuario1.getNombre() + " por un monto de: " + _Monto);
                txtRutDes.setText("");
                txtDestino.setText("");
                txtNombreDes.setText("");
                txtMonto.setText("");
                oPantallaP = new PantallaP(rutVolver);
                oPantallaP.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Monto invalido");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Transferir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private String getRutUsuario(int n_cuenta) {
        try {
            oDao = new DAO();
            String rutV;
            rutV = oDao.getRutUsuario(n_cuenta);
            return rutV;
        } catch (SQLException ex) {
            Logger.getLogger(Transferir.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    private void getUsuario(String r_Usuario) {

        try {
            oDao = new DAO();
            Usuario oUsuario;
            oUsuario = oDao.getUserRegisted(r_Usuario);
            if (oUsuario != null) {
                txtDestino.setText(String.valueOf(oUsuario.getN_cuenta()));
                txtNombreDes.setText(oUsuario.getNombre());
                chbConfirmar.setEnabled(true);
                txtCorreo.setText(oUsuario.getCorreo());
                String n = oUsuario.getCorreo();
            }
        } catch (SQLException ex) {
            Logger.getLogger(PantallaP.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

}
